kind: pipeline
type: docker
name: default

steps:
- name: build-dockerhub
  image: plugins/docker
  settings:
    repo: neredera/disk_usage-exporter
    tags:
      - latest
    username:
      from_secret: dockerhub_user
    password:
      from_secret: dockerhub_password

- name: build-nere-int
  image: plugins/docker
#  image: nere.dev/d-hub/plugins/docker:latest
  settings:
#    mirror: https://nere.dev/d-int
    repo: nere.dev/d-int/disk_usage_exporter
    registry: nere.dev/d-int
    tags:
      - latest

