kind: pipeline
type: docker
name: default

steps:
- name: build
  image: plugins/docker
#  image: nere.dev/d-hub/plugins/docker:latest
  settings:
#    mirror: https://nere.dev/d-int
    repo: nere.dev/d-int/disk_usage_exporter
    registry: nere.dev/d-int
    tags:
      - latest
